/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.NumerosRacionais;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class TelaNumerosRacionais extends javax.swing.JFrame {

    NumerosRacionais objeto1;
    NumerosRacionais objeto2;   

    /**
     * Creates new form TelaNumerosRacionais
     */
    public TelaNumerosRacionais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNumerador1 = new javax.swing.JTextField();
        jtDenominador1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaida = new javax.swing.JTextArea();
        jButtonSoma = new javax.swing.JButton();
        jButtonSubtracao = new javax.swing.JButton();
        jButtonMultiplicacao = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();
        jButtonIgualdade = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtNumerador2 = new javax.swing.JTextField();
        jtDenominador2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Números Racionais");

        jLabel1.setText("Numerador");

        jLabel2.setText("Denominador");

        jTextAreaSaida.setColumns(20);
        jTextAreaSaida.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaida);

        jButtonSoma.setText("+");
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });

        jButtonSubtracao.setText("-");
        jButtonSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtracaoActionPerformed(evt);
            }
        });

        jButtonMultiplicacao.setText("*");
        jButtonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacaoActionPerformed(evt);
            }
        });

        jButtonDivisao.setText("/");
        jButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisaoActionPerformed(evt);
            }
        });

        jButtonIgualdade.setText("==");
        jButtonIgualdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualdadeActionPerformed(evt);
            }
        });

        jLabel3.setText("Racion 1");

        jLabel4.setText("Racion 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSoma)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSubtracao)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMultiplicacao)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDivisao)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIgualdade))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtNumerador1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(jtDenominador1))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtDenominador2)
                            .addComponent(jtNumerador2))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNumerador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNumerador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtDenominador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDenominador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSoma)
                    .addComponent(jButtonSubtracao)
                    .addComponent(jButtonMultiplicacao)
                    .addComponent(jButtonDivisao)
                    .addComponent(jButtonIgualdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed

        try {
            objeto1 = new NumerosRacionais();
            objeto1.set(Integer.parseInt(jtNumerador1.getText()),
                   Integer.parseInt(jtDenominador1.getText()));

            
            objeto2 = new NumerosRacionais(Integer.parseInt(jtNumerador2.getText()),
                    Integer.parseInt(jtDenominador2.getText()));
            
           NumerosRacionais auxAdicao = objeto1.adicionar(objeto2);
            String saida = "Adição: " + auxAdicao.get() + "\n";
            jTextAreaSaida.setText(saida);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
        // auxSubtracao = objeto1.subtrair(objeto2);
        // String saida = "Testando MDC: " +   objeto1.calcularMDC(objeto2) + "\n";
        //saida = "Testando MMC: " + objeto1.calcularMMC(objeto2) + "\n";
    }//GEN-LAST:event_jButtonSomaActionPerformed

    private void jButtonSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtracaoActionPerformed

        try {
            objeto1 = new NumerosRacionais();
            objeto1.set(Integer.parseInt(jtNumerador1.getText()),
                    Integer.parseInt(jtDenominador1.getText()));
            
            objeto2 = new NumerosRacionais(Integer.parseInt(jtNumerador2.getText()),
                    Integer.parseInt(jtDenominador2.getText()));
            
          NumerosRacionais  aux = objeto1.subtrair(objeto2);
          
            String saida = "Subtração: " + aux.get() + "\n";
            jTextAreaSaida.setText(saida);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonSubtracaoActionPerformed

    private void jButtonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacaoActionPerformed
        try {
            objeto1 = new NumerosRacionais();
            objeto1.set(Integer.parseInt(jtNumerador1.getText()),
                    Integer.parseInt(jtDenominador1.getText()));
            
            objeto2 = new NumerosRacionais(Integer.parseInt(jtNumerador2.getText()),
                    Integer.parseInt(jtDenominador2.getText()));
          NumerosRacionais  auxMultiplicacao = objeto1.multiplicar(objeto2);
            String saida = "Multiplicação: " + auxMultiplicacao.get() + "\n";
            jTextAreaSaida.setText(saida);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }


    }//GEN-LAST:event_jButtonMultiplicacaoActionPerformed

    private void jButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisaoActionPerformed
        try { 
            objeto1 = new NumerosRacionais();
            objeto1.set(Integer.parseInt(jtNumerador1.getText()),
                    Integer.parseInt(jtDenominador1.getText()));
            
            objeto2 = new NumerosRacionais(Integer.parseInt(jtNumerador2.getText()),
                    Integer.parseInt(jtDenominador2.getText()));
          NumerosRacionais  auxDivisao = objeto1.dividir(objeto2);
            String saida = "Divisão: " + auxDivisao.get() + "\n";
            jTextAreaSaida.setText(saida);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }        
    }//GEN-LAST:event_jButtonDivisaoActionPerformed

    private void jButtonIgualdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualdadeActionPerformed
        try {  
            objeto1 = new NumerosRacionais();
            objeto1.set(Integer.parseInt(jtNumerador1.getText()),
                    Integer.parseInt(jtDenominador1.getText()));
            
            objeto2 = new NumerosRacionais(Integer.parseInt(jtNumerador2.getText()),
                    Integer.parseInt(jtDenominador2.getText()));
            String saida = "";
            if (objeto1.compararIgualdade(objeto2)==true){                
         saida = "São iguais ? : SIM";                
            }else {                
                saida = "São iguais ? : NÃO";
            }            
        jTextAreaSaida.setText(saida);           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }        
    }//GEN-LAST:event_jButtonIgualdadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNumerosRacionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNumerosRacionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNumerosRacionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNumerosRacionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNumerosRacionais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonIgualdade;
    private javax.swing.JButton jButtonMultiplicacao;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JButton jButtonSubtracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaida;
    private javax.swing.JTextField jtDenominador1;
    private javax.swing.JTextField jtDenominador2;
    private javax.swing.JTextField jtNumerador1;
    private javax.swing.JTextField jtNumerador2;
    // End of variables declaration//GEN-END:variables

}
